import React from 'react';
import { ShieldIcon } from './icons';

interface DisclaimerModalProps {
    onClose: () => void;
}

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ onClose }) => {
    return (
        <div
            className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-fade-in"
            onClick={onClose}
        >
            <div
                className="w-full max-w-2xl h-[90vh] max-h-[600px] bg-slate-800 border-2 border-slate-700 rounded-lg shadow-2xl shadow-purple-900/40 flex flex-col"
                onClick={(e) => e.stopPropagation()}
            >
                <header className="p-4 border-b border-slate-700 flex items-center justify-between flex-shrink-0">
                    <div className="flex items-center gap-3">
                        <ShieldIcon className="w-8 h-8 text-purple-400" />
                        <h2 className="font-cinzel text-2xl font-bold text-white">Disclaimer & Terms of Use</h2>
                    </div>
                </header>

                <main className="flex-1 overflow-y-auto p-6 space-y-4 text-slate-300">
                    <p>
                        Welcome to Magicians' AI Wizard! This tool is designed to be a creative partner for magicians. By using this service, you agree to the following terms:
                    </p>

                    <div>
                        <h3 className="font-bold text-white mb-1">AI-Generated Content</h3>
                        <p>
                            The content, scripts, ideas, and advice provided by the Magicians' AI Wizard ("the Service") are generated by an artificial intelligence. While we strive for creativity and accuracy, the information is provided for <strong className="font-semibold text-amber-300">inspirational and educational purposes only.</strong>
                        </p>
                    </div>

                    <div>
                        <h3 className="font-bold text-white mb-1">No Guarantees</h3>
                        <p>
                            The Service makes no warranties or guarantees regarding the effectiveness, safety, or success of any magic trick, script, or performance suggestion. The art of magic is dependent on skill, practice, and performance context.
                        </p>
                    </div>
                    
                    <div>
                        <h3 className="font-bold text-white mb-1">User Responsibility</h3>
                        <p>
                            You, the user, are solely responsible for your performance and the application of any information obtained from this Service. You assume all risks associated with performing magic tricks, including but not limited to audience reaction, prop failure, or personal injury. Always practice safely.
                        </p>
                    </div>

                    <div>
                        <h3 className="font-bold text-white mb-1">Limitation of Liability</h3>
                        <p>
                            Magicians' AI Wizard, LLC and its affiliates shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the Service.
                        </p>
                    </div>

                     <div>
                        <h3 className="font-bold text-white mb-1">Ethical Use</h3>
                        <p>
                            This tool is intended to foster creativity, not to maliciously expose the secrets of magic. Please use the knowledge gained responsibly and ethically to preserve and advance the art of magic.
                        </p>
                    </div>
                    <p className="pt-4 text-center text-slate-400">
                        By continuing to use this Service, you acknowledge and agree to these terms.
                    </p>

                </main>
                <footer className="p-4 border-t border-slate-700 flex-shrink-0 flex justify-end">
                     <button onClick={onClose} className="px-6 py-2 bg-purple-600 hover:bg-purple-700 rounded-md text-white font-bold transition-colors">
                        I Understand
                    </button>
                </footer>
            </div>
        </div>
    );
};

export default DisclaimerModal;